# Generated by Django 3.2.7 on 2021-09-24 19:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainshop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Podcast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Наименование')),
                ('slug', models.SlugField(unique=True)),
                ('image', models.ImageField(upload_to='', verbose_name='Изображение')),
                ('description', models.TextField(null=True, verbose_name='Описание')),
                ('price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Цена')),
                ('studio', models.CharField(max_length=255, verbose_name='Студия')),
                ('duration', models.CharField(max_length=30, verbose_name='Длительность')),
                ('kolvo_ep', models.CharField(max_length=255, verbose_name='Количество выпусков')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainshop.category', verbose_name='Категория')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Наименование')),
                ('slug', models.SlugField(unique=True)),
                ('image', models.ImageField(upload_to='', verbose_name='Изображение')),
                ('description', models.TextField(null=True, verbose_name='Описание')),
                ('price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Цена')),
                ('genre', models.CharField(max_length=255, verbose_name='Жанр')),
                ('author', models.CharField(max_length=255, verbose_name='Автор')),
                ('year', models.CharField(max_length=30, verbose_name='Год издания')),
                ('price_of_pdf', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Цена эл. версии')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainshop.category', verbose_name='Категория')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Audiobook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Наименование')),
                ('slug', models.SlugField(unique=True)),
                ('image', models.ImageField(upload_to='', verbose_name='Изображение')),
                ('description', models.TextField(null=True, verbose_name='Описание')),
                ('price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Цена')),
                ('genre', models.CharField(max_length=255, verbose_name='Жанр')),
                ('author', models.CharField(max_length=255, verbose_name='Автор')),
                ('year', models.CharField(max_length=30, verbose_name='Год издания')),
                ('duration', models.CharField(max_length=30, verbose_name='Длительность')),
                ('dictor', models.CharField(max_length=35, verbose_name='Диктор')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainshop.category', verbose_name='Категория')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
